const nome = prompt('qual o seu nome') 
const comida1 = prompt("qual sua comida favorita")
const comida2 = prompt("qual sua comida favorita")
const comida3 = prompt("qual sua comida favorita")   
console.log(`essas são suas comidas favoritas ${nome} \n -${comida1} \n -${comida2} \n -${comida3}`)