let nomeDeUsuario = prompt("Qual o seu nome?")
let comida1 = prompt("Digite sua primeira comida favorita")
let comida2 = prompt("Digite sua segunda comida favorita")
let comida3 = prompt("Digite sua terceira comida favorita")
console.log("Essas são as comidas favoritas de "+nomeDeUsuario+"\n-"+comida1+ "\n-"+comida2+"\n-"+comida3)